### ISSUE TITLE
Add tests for convergence and correctness

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#114]
Add tests to the CI to make sure that the solution is correct, that the exit status is "converged", and whatever else we figure out by then.

**Comment by abelsiqueira** [comment]
Do we have a better idea of what we want here?

**Comment by datejada** [comment]
@abelsiqueira, to be fair, we are good with the "optimal" and "infeasible" states. I recall that Laurent proposed it, but this will make more sense for iterative runs of the model (like a Benders' decomposition technique); since we are not doing that type of technique yet, I propose to close it and, if needed, in the future we can open a new issue (with more details and specifications).
