### ISSUE TITLE
Compare to a model without Sets and dictionaries

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#16]
Currently, the model creates dictionaries to obtain the parameter values.
For instance,

```julia
p_variable_cost   = Dict((row.a)                => row.pVarCost for row in eachrow(assets_df))
```

This is needed because the model is indexed by the values of the sets. For instance,

```julia
A = assets_df.a
...
@variable(model, 0 <= v_float[A,...])
```

Instead, we can index via the numerical index of the set:

```julia
num_assets = length(assets_df.a)
A = 1:num_assets
...
p_variable_cost = assets_df.pVarCost
```

However, to do this, the parameters `p_demand` and `p_availability` would need some extra attention, since they are not, technically, 1-dimensional.
If it is possible to create this version, a comparison will help decide which strategy to follow.

**Comment by datejada** [comment]
Hi Abel,

My main concern with having numbers instead of names in the variables/constraints is that if the model is infeasible (for whatever reason), the solvers usually return information about the infeasibility, e.g., the variable and constraint that make the problem infeasible. So, if you have names in the variables, it is easier to debug the problem. For instance, having a message with "v_flow_wind,rp3,k01_" is more meaningful than "v_flow_4,3,1_".

In any case, it is good to test the performance because if there is an advantage when having numbers, then we can ponder the options.

**Comment by clizbe** [comment]
Abel determined this is unuseful.
