### ISSUE TITLE
Catch warning from infeasible test

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#190]
### Summary

There is a `@test_logs` function for that: https://docs.julialang.org/en/v1/stdlib/Test/#Testing-Log-Statements

### Basic Example

```julia
@test_logs (:warning, "Something, something, dark side") solve_model...
```

### Drawbacks

none

**Comment by datejada** [comment]
Unfortunately @clizbe, it breaks for Julia 1.6 in all the OS (Ubuntu, Mac, Windows). Using the latest version of Julia, it doesn't break. We didn't catch that in the PR since we are only testing for Julia version 1 and locally at the latest version. So, we might want to have a change that fits all the versions we want to have support (i.e., 1, 1.6, latest). @abelsiqueira, what do you think?

**Comment by clizbe** [comment]
Yeah I was afraid that might happen - it's because some features of "test" are only in the most recent Julia. I'll see if there's another catch for what I want to do that's backwards compatible.

**Comment by clizbe** [comment]
Actually I think it's because the one I used is deprecated. Haha sorry @abelsiqueira, I tried using test_logs but couldn't figure it out so switched to something else. I figured out test_logs now so I think it'll work. :)
