### ISSUE TITLE
Consider changing flow id to from, to pair in the CSV files

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#269]
### What and Why

Edit: This is only for the CSV files, not the model.

The graph is indexed on the `(from,to)` pair labels. The ids are not used or stored explicitly.
Implicitly they are required because the profiles and partition CSVs use the flow ids. This means that to add this information to the graph structure, we have to use the `flow_data` vector and look at its keys. This is the reason for the ugly code that @datejada comment in the other PR: `flow_data[id][1]`. The `1` is referring to the key.

### Possible Drawbacks

- Requires changing many files.
- The data becomes more verbose.

**Comment by datejada** [comment]
We always come back to the dilemma of using `number` (i.e., ids) of `label` (i.e., name) in the formulation 🤔 

As we have discussed before, Ids are fine as long as we can have the names when we have an infeasible problem.

**Comment by abelsiqueira** [comment]
This is not in the model, this only affects the CSV files.

**Comment by datejada** [comment]
Ah! I get it now. So, let's change the files. Using the ids was utterly arbitrary, and we don't have any particular reason right now to use them instead of the ids. We are on time to do it.

So, if I get it right now, we have this in the CSV files for the assets profiles:

,,,p.u.
id,rep_period_id,time_step,value
3,1,1,0.11

And we want this:

,,,p.u.
name,rep_period_id,time_step,value
wind,1,1,0.11

Is that correct? And, of course, change the i/o, graph creating, etc...

**Comment by abelsiqueira** [comment]
Yes!

**Comment by datejada** [comment]
@abelsiqueira If you are not working on this, I can take it over and do this change 😄

**Comment by abelsiqueira** [comment]
I started it and - hopefully - will finish it soon. There are more changes that I predicted.
