### ISSUE TITLE
Create a function to export the whole solution to file (e.g., CSV, parquet, JSON, etc.)

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#295]
Currently, we only export the assets investment.

**Comment by abelsiqueira** [comment]
Related to #115

**Comment by abelsiqueira** [comment]
How should we write the `flow` output? It is indexed in `(u,v)`, `rp`, and `B`, where `B` is the time block.

- Do we write the whole time block variable as a column?
- Or do we divide the flow value between all time steps?

I.e., if `flow[("a","b"), 1, 1:3] = 30.0`, should we write

```
from,to,rp,B,value
a,b,1,1:3,30.0
```

or

```
from,to,rp,time_step,value
a,b,1,1,10.0
a,b,1,2,10.0
a,b,1,3,10.0
```

**Comment by clizbe** [comment]
Personally I prefer the second, but I guess it depends how you want to analyse the data.
@gnawin What do you think?

**Comment by gnawin** [comment]
@clizbe For me as well the second is more useful, because it makes it easier to manipulate the results further.

I have another conceptual question though, if `flow[("a","b"), 1, 1:3] = 30`, does it mean `flow[("a","b"), 1, 1] = flow[("a","b"), 1, 2] = flow[("a","b"), 1, 3] = 30` or `flow[("a","b"), 1, 1] = flow[("a","b"), 1, 2] = flow[("a","b"), 1, 3] = 10`? 
Or more generally, when we define any variable over a time block, is the value the sum over the time block, or of every time step in the time block? @datejada @abelsiqueira

**Comment by clizbe** [comment]
For storage it's energy, for flows it's power. We should add this explanation of exactly what the output means to the documentation.

**Comment by datejada** [comment]
With @suvayu, we discussed the new duckDB workflow, which will cover this part as well as exporting the outputs to other types of files. So, we added it to the epic issue #289

**Comment by abelsiqueira** [comment]
I will create a simple version to be used right now, independent of DuckDB.
