### ISSUE TITLE
Check if JuMP is threaded

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaEnergyModel.jl#338]
Are for loops in parallel?

**Comment by clizbe** [comment]
According to this convo, there's only 3-4 (see comments for 4th) ways to multi-thread a JuMP model.
https://stackoverflow.com/questions/64177415/create-jump-model-with-multi-threading-in-julia

**Comment by clizbe** [comment]
This one says every thread should have a copy of the model and you can't pass copies between threads. Which sounds like one of the methods above:
https://discourse.julialang.org/t/multithreading-unstable-with-jump/49494/2

**Comment by clizbe** [comment]
Okay - it'd be cool if we could tell it "run these 5 scenarios" and it would run as many copies of the model in parallel as it can.

**Comment by datejada** [comment]
@abelsiqueira Even though we closed this issue, I'm curious about the implementation here for SpineOpt https://github.com/spine-tools/SpineOpt.jl/commit/516f408bfbd8a5cf2e0ba01142fa9366e788829d
Do you think that is anything that we can apply for Tulipa? or is it mainly due to their way of building the model that they can exploit this option?

**Comment by abelsiqueira** [comment]
No idea. At a glance, I can't tell. It could be that building constraints work in parallel, and the JuMP docs are not explicit enough on what works or not. Maybe reopen this for a more complete investigation?
