### ISSUE TITLE
Move TulipaPlots to separate repo

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#451]
### What and Why

It's better that way

### Description
- [x] Create new repo TulipaPlots.jl: https://github.com/TulipaEnergy/TulipaPlots.jl
- [x] Move all relevant items from TulipaEnergyModel.jl to TulipaPlots.jl
- [x] Remove those items in TulipaEnergyModel.jl

**Comment by gnawin** [comment]
I have migrated the inputs to TulipaPlots.jl in order to run the Norse case there and plot in the test. I figured out there is a caveat that the inputs and the model version may not always match, which causes errors. For example, I updated to the latest version of TulipaEnergyModel.jl, which introduces some changes in the inputs. Unless I manually also update the inputs, errors occur. 

There are two things I can do:
- Make sure when the TulipaEnergyModel.jl is updated, also update the inputs. This is a maintenance issue. And I am not sure if any future updates may break the code for plotting.
- Do not run the scenarios, but only use the solution as input. This is currently under development in the IO pkg I think.

@abelsiqueira what do you think?

**Comment by abelsiqueira** [comment]
I would use fake data that does not depend on the energy model at all (if possible). I think only the `graph` object is necessary (even from within the `EnergyProblem`, right? Maybe creating a fake one is enough?

On the other hand, the `graph` itself might change (and possibly will), so I am not sure how feasible this approach would be.
