### ISSUE TITLE
Update the GitHub actions for testing in the main branch

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#481]
### What and Why

The nightly version is currently failing due to compatibility issues with the CSV package. To avoid future issues, we should change the action to allow failures on that version.

### Possible Drawbacks

The users may be unaware that the nightly version is not supported. I don't know if that is a drawback.

**Comment by abelsiqueira** [comment]
Nightly is not expected to work, so it is fine. It is sometimes useful to have nightly in the tests to see possible failures, however, since we depend on some lower-level packages, like CSV, and maybe JuMP and HiGHS, then it makes it likely to fail because of them. I think it is fine to drop the tests until 1.0 is released, but if that is too extreme, we should definitely mark as allow-failure, that was an oversight on my part.

**Comment by abelsiqueira** [comment]
Nightly was removed in #496
