### ISSUE TITLE
Add How-To for different level of investment detail

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#530]
We can add a section showing how to define different levels of detail in the model for investment decisions. So far, the model has only the investment in one year and two parameters in the input data that can give you a couple of options: 

- `investable`:  to determine if you want to invest or not in the asset
- `investment_integer`: to determine if the investment of the asset is integer or linear

Therefore, for the same run, you can have assets that the investment is integer (e.g., electrolizer, ccgt, etc) or linear (e.g., solar, wind, batteries).

@g-moralesespana, Do you have more parameters and options in mind for the single-year investment? thinking about the different levels of detail.

**Comment by g-moralesespana** [comment]
The integer or linear investment could apply to any technology. It would also be nice to have an overruling parameter somewhere, where we could say all investments are linear, so we do not need to go technology by technology to change them, and change them back. About the different levels of detail, for sure it should apply to the investment, but also to the operation. So I do not know if it should be only investment-related. Mmm I think my answer did not help to clarify.

**Comment by datejada** [comment]
> The integer or linear investment should apply to any technology. It would also be nice to have an overruling parameter somewhere, where we could say all investments are linear, so we do not need to go technology by technology to change them, and change them back. About the different levels of detail, for sure it should apply to the investment, but also to the operation. So I do not know if it should be only investment-related. Mmm I think my answer did not help to clarify.

Thanks! Regarding the different levels of detail, there are two different tasks in the project schedule: one for investments for Milestone 1 and another for operation for Milestone 3. So, here, the focus is on the different levels of detail for investments. The overruling parameter will be part of the transformations that @suvayu is adding to TulipaIO since this is where the user will manipulate the initial input data. So, Milestone 1 of TulipaEnergyModel will be enough with the linear/integer option we have now in the code (for the different levels of detail on investment). Do you agree? @g-moralesespana @clizbe
