### ISSUE TITLE
Remove test using Tiny/bad-assets-data.csv (and file)

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaEnergyModel.jl#812]
### What and Why

This file was used for testing and is out of date. If we still use it, we should update it. Otherwise, remove.

**Comment by datejada** [comment]
We use it to test if the type defined in the data differs from the one specified in the code (e.g., Integer and then having a String in the file). It doesn't need to be updated since the idea is to test that you get an error if you read a file with a bad schema; see the screenshot below:

<img width="410" alt="image" src="https://github.com/user-attachments/assets/a89acd63-8447-4848-8988-12608168a261">

So, I don't think this is an issue. But, just in case, let's double-check with @suvayu before closing it, who was the person who recommended this test at the beginning 😄

**Comment by suvayu** [comment]
Indeed, testing for malformed/incorrect input files is a good thing, but I don't think that test actually does that.  The test is actually "testing" if the dict holding all the schemas has a schema called "bad_assets_data", which is not really a useful test.  In pseudo-code, the test should look like this:

```julia
schema = TEM.get_schema("assets_data")
@test_throws <ExceptionType> TIO.create_tbl(con, ...; types = schema)
```

Ideally you would catch a specific exception, but if that's not possible you should also check the error message.  So if the `<ExceptionType>` is `ErrorException`, there should be a follow-up like this:
```julia
@test_throws r"<regex matching message>" TIO.create_tbl(con, "/path/to/bad_assets_data.csv"; types = schema)
```

The code duplication is unavoidable due to Julia testing library limitations.  You can see this [example from TIO](https://github.com/TulipaEnergy/TulipaIO.jl/blob/e75695db78363c3eb8761abab5ffdbcbb82948c4/test/test-pipeline.jl#L58-L63).

**Comment by suvayu** [comment]
Actually, you can drop this test, because this should be tested in TIO, which I think it [already is](https://github.com/TulipaEnergy/TulipaIO.jl/blob/e75695db78363c3eb8761abab5ffdbcbb82948c4/test/test-pipeline.jl#L84-L92).
