### ISSUE TITLE
Map ESDL to a Julia data structure (assets data, flows data, and graph)

### ISSUE THREAD

**Issue by lsoucasse** [TulipaEnergy/TulipaEnergyModel.jl#89]
Go through the ESDL file and map ports to connections to create a graph in Julia.

The esdl ports link to a hash that later must be scanned to find the right connection.

Also, obtain the assets and flows data

---
Removed the following because this will happen before GML+CSV are created, i.e., before Julia is involved.
~Possible implementation~
- ~represent graph data structure using [GraphIO.jl](https://github.com/JuliaGraphs/GraphIO.jl)~

**Comment by datejada** [comment]
@Alfa-R

**Comment by sjvrijn** [comment]
@lsoucasse https://github.com/TulipaEnergy/TulipaEnergyModel.jl/pull/226 has an initial implementation to take an ESDL file and process it into a directed flow graph.
There are some tests for correctly reading instances/assets, but to test the graph construction, I'd prefer to visually build a few graphs rather than trying to edit an existing ESDL file into something manageable and correct.

At least it should save some of the leg work and provide an example of how to work with the XML package if anything else is needed.

**Comment by clizbe** [comment]
Should it now be like this?
ESDL > JSON > Julia data structure

**Comment by abelsiqueira** [comment]
Just to disrupt this thread a bit, it has been announced in the JuliaCon Local Eindhoven that a package for dealing with XSD will be made available. There is no timeline yet, since it has been developed inside ASML, and they need approval to make it public.

If I understand it correctly, this tool should enable doing with Julia what it is being done with Python (i.e., create structures and read the data directly into these structures), though I am not sure if XSD is enough or not.

The XSD package does NOT cover the full XSD specification yet, though, so we might still need to do some work to make ESDL work with it.

We should check again in a few weeks.

**Comment by Lokkij** [comment]
That's great news! XSD support should be sufficient to properly handle ESDL. I don't want to delay the input handling for the project too much, though - if we think XSD support is going to take a long time, it's probably worth it to make a temporary (JSON-based?) implementation so we can make progress.

**Comment by suvayu** [comment]
Close in favour of #358
