### ISSUE TITLE
Change the default of the `enable_names` option to false in the `create_model` function

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#937]
### Description

We create the model with names for debugging purposes. However, this can increase the model creation by 30% (see https://github.com/TulipaEnergy/TulipaEnergyModel.jl/pull/936). So, it will be better to have this option as false by default, but we need to update the docs and provide an example to show users how to enable the names for debugging.

Actions:

- [ ] ~Change the default value in the function~
- [x] Create a how-to in the docs showing how to enable the names and the implications of the time creation

**Comment by clizbe** [comment]
Stealing Jody's logic when discussing SpineOpt, I think it makes more sense to have `enable_names = true` as the default (but disable it in the tests) so that new users don't have to go digging to figure out what's happening. We can teach about disabling it for speed in our docs, and include it in the tutorials.

But open for discussion!
